version: '3.8'

services:
  # GPU-enabled version (default)
  speaker-profiles-gpu:
    build:
      context: .
      dockerfile: Dockerfile
    image: speaker-profiles:gpu
    container_name: speaker-profiles-gpu
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    env_file:
      - .env.docker
    volumes:
      # Mount audio files directory
      - ../audio:/app/audio:ro
      # Mount speakers database (persistent)
      - ../speakers:/app/speakers
      # Mount output directory
      - ../output:/app/output
      # Mount pretrained models cache (persistent)
      - speaker-models-cache:/app/pretrained_models
      # Optional: mount custom config
      - ./.env.docker:/app/.env:ro
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: ["bash"]

  # CPU-only version (fallback)
  speaker-profiles-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    image: speaker-profiles:cpu
    container_name: speaker-profiles-cpu
    environment:
      - CUDA_VISIBLE_DEVICES=""
    env_file:
      - .env.docker
    volumes:
      # Mount audio files directory
      - ../audio:/app/audio:ro
      # Mount speakers database (persistent)
      - ../speakers:/app/speakers
      # Mount output directory
      - ../output:/app/output
      # Mount pretrained models cache (persistent)
      - speaker-models-cache-cpu:/app/pretrained_models
      # Optional: mount custom config
      - ./.env.docker:/app/.env:ro
    ports:
      - "8001:8000"
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: ["bash"]

  # Development version with hot-reload
  speaker-profiles-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: speaker-profiles:dev
    container_name: speaker-profiles-dev
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PYTHONUNBUFFERED=1
    env_file:
      - .env.docker
    volumes:
      # Mount the entire project for development
      - ..:/app/project:ro
      # Mount individual directories for persistence
      - ../audio:/app/audio:ro
      - ../speakers:/app/speakers
      - ../output:/app/output
      - speaker-models-cache:/app/pretrained_models
      # Development: mount source code for live editing
      - ../:/app/src:ro
    working_dir: /app/src
    ports:
      - "8002:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: ["bash"]

volumes:
  # Persistent model cache for GPU version
  speaker-models-cache:
    driver: local
  
  # Persistent model cache for CPU version  
  speaker-models-cache-cpu:
    driver: local

networks:
  default:
    name: speaker-profiles-network